baseURL = 'https://amemiya02.github.io'
languageCode = 'zh-CN'
title = '个人技术博客'
theme = "PaperMod"

[pagination]
  pagerSize = 10
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'],['$', '$']]
[params]
    env = "production"
    math = true
    ShowFullPagination = true
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowToc = true
    # 个人主页模式
    [params.profileMode]
        enabled = true
        title = "Amemiya"
        subtitle = "欢迎来的我的个人博客"
        imageUrl = "avatar.jpg"
        [[params.profileMode.buttons]]
            name = "文章列表"
            url = "posts"
        [[params.profileMode.buttons]]
            name = "标签列表"
            url = "tags"
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/amemiya02"
